# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

env:
  global:
    - CODECOV_TOKEN="213374d1-b80c-43f0-b874-81777304187d"
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - ignatow.n@mail.ru
    on_success: never # default: change
    on_failure: always # default: always